'use strict';

const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+name)?.classList.add('active');$$('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#crumb').textContent=name==='inicio'?'Inicio':({temas:'Explorar temas',videos:'Videotutoriales',laboratorio:'Laboratorio gráfico',retos:'Ejercicios y retos',materiales:'Materiales',equipo:'Equipo'}[name]||'Tema');$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function openTopic(n){const t=topics.find(x=>x.n===Number(n));if(!t)return;$('#topicCode').textContent=`PRE-${String(t.n).padStart(2,'0')} · ${t.type}`;$('#topicTitle').textContent=t.title;$('#topicIntro').textContent=t.intro;$('#topicFormula').textContent=t.formula;$('#topicProps').textContent=t.props;$('#topicFacts').innerHTML=`<div><span>01</span><span>${t.type}</span></div><div><span>02</span><span>Ejercicio guiado</span></div><div><span>03</span><span>${t.duration} min</span></div><div><span>04</span><span>Videotutorial</span></div>`;$('#exampleTitle').textContent=t.example;$('#exampleIntro').textContent='Procedimiento organizado en pasos para que el resultado pueda comprobarse al finalizar.';$('#steps').innerHTML=t.steps.map(s=>`<li>${s}</li>`).join('');$('#checkText').textContent='Use el resultado del ejemplo para verificar la resolución.';$('#checkResult').textContent='';$('#graphText').textContent=t.n===9?'La parábola permite observar el vértice, el eje de simetría, las raíces y la intersección con el eje y.':t.n===10?'La gráfica de un polinomio ayuda a relacionar sus ceros con los cruces o contactos con el eje x.':'La gráfica debe leerse relacionando coordenadas y características de la función.';$('#practiceText').textContent=t.n===9?'Para f(x)=x²−6x+5, determine el vértice.':'Para f(x)=x³−6x²+11x−6, determine los ceros reales.';$('#videoCode').textContent=`PRE-${String(t.n).padStart(2,'0')}`;$('#videoDuration').textContent=t.duration+' min';$('#videoDesc').textContent=`Videotutorial sobre: ${t.example}. El espacio está preparado para integrar el video del integrante responsable del tema.`;$('#videoFormulas').innerHTML=`<div class="formula"><small>Referencia principal</small><strong>${t.formula}</strong></div>`;$('#timestamps').innerHTML=['00:00 Presentación del ejercicio','00:40 Identificación de datos','01:30 Desarrollo','03:10 Comprobación'].map(x=>{let [time,...rest]=x.split(' ');return `<li><button><time>${time}</time><span>${rest.join(' ')}</span></button></li>`}).join('');$$('.lesson-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='conceptos'));$$('.lesson-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel==='conceptos'));showView('topic')}
function build(){const tn=$('#topicNav');tn.innerHTML=topics.map(t=>`<button data-topic="${t.n}">PRE-${String(t.n).padStart(2,'0')} · ${t.title}</button>`).join('');$('#topicGrid').innerHTML=topics.map(t=>`<div class="topic-row" data-topic="${t.n}"><span class="code">PRE-${String(t.n).padStart(2,'0')}</span><div><h3>${t.title}</h3><p>${t.desc}</p></div><span class="topic-type">${t.type}</span><span class="arrow">→</span></div>`).join('');$('#videoTable').innerHTML=`<div class="vrow vhead"><span>Código</span><span>Ejercicio</span><span>Duración</span><span>Recurso</span></div>`+videos.map(v=>`<div class="vrow"><span class="code">${v.code}</span><span>${v.title}<small class="muted" style="display:block">${v.topic}</small></span><span class="muted">${v.duration}</span><a href="#" data-topic="${v.code.split('-')[1]}">Ver tutorial →</a></div>`).join('')}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){e.preventDefault();showView(view.dataset.view);return}const topic=e.target.closest('[data-topic]');if(topic){e.preventDefault();openTopic(topic.dataset.topic);return}const tab=e.target.closest('[data-tab]');if(tab){const n=tab.dataset.tab;$('.lesson-nav button').forEach(b=>b.classList.toggle('active',b===tab));$('.lesson-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===n));return}if(e.target.id==='showCheck'){const t=topics.find(x=>$('#topicTitle').textContent===x.title);$('#checkResult').textContent=t?.check||''}if(e.target.id==='checkPractice'){const ans=$('#answer').value.trim();$('#practiceResult').textContent=ans?'Respuesta registrada para revisión.':'Escriba una respuesta antes de comprobar.'}});

try{build()}catch(error){console.error('Error al construir el contenido:',error)}

$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$('#topicGrid .topic-row').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'grid':'none')});
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('#topicGrid .topic-row').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'grid':'none')});